### PR TITLE
implement #41

### PR DESCRIPTION
**Pull request by baentsch**
@xvzcf Anything (else) missing? If so, please update #41

### CODE REVIEW

**Comment by xvzcf** [comment]
Could you update this PR (or open a new one) that just adds `psutil` to the images?

**Comment by baentsch** [comment]
So done. I left in `go` as comments so we could easily add it if/when the need arises.

**Comment by baentsch** [comment]
@xvzcf Any objections I add Java support on top to only necessitate one round of docker image building?

**Comment by xvzcf** [comment]
> @xvzcf Any objections I add Java support on top to only necessitate one round of docker image building?

None.

**Comment by baentsch** [comment]
@dstebila As discussed in/for https://github.com/open-quantum-safe/liboqs-java/issues/4, ubuntu and debian images updated . If OK for you, please build and push to docker hub.

**Comment by baentsch** [comment]
Rebase done. Test ran OK at https://app.circleci.com/pipelines/github/baentsch/testing/57/workflows/a4e0c0c1-2bd5-4626-931c-95e1fffc2cb2 
@dstebila @xvzcf I'll squash and merge by end of day if I don't hear anything to the opposite from you

**Pull request merged**
